server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  config-location: classpath:mybatis.xml

debug: true

md5: ark

